### ISSUE TITLE
0.3.0 fails to compile on macOS

### ISSUE THREAD

**Issue by bdrelling** [Open-Bytes/SwiftUINavigator#2]
Your project doesn't integrate into a macOS project. See errors below.

I would have loved to use this package, but will likely need to find another solution now.

```
Showing Recent Messages
CompileSwift normal arm64 /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift (in target 'SwiftUINavigator' from project 'SwiftUINavigator')
    cd /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator
    /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/BackStack.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/BottomSheet/BottomSheet.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/DismissLink.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/Extensions/View+OnDataChange.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/LazyView.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/LargeNavBar.swift -primary-file /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavManager.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavigationType.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/Navigator.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavigatorLink.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavigatorTransitionType.swift /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavigatorView.swift -emit-dependencies-path /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/Objects-normal/arm64/NavBar.d -emit-reference-dependencies-path /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/Objects-normal/arm64/NavBar.swiftdeps -serialize-diagnostics-path /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/Objects-normal/arm64/NavBar.dia -target arm64-apple-macos10.15 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Products/Debug -I /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Products/Debug -F /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -enable-testing -g -module-cache-path /users/redacted/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -profile-generate -profile-coverage-mapping -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -new-driver-path /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -serialize-debugging-options -Xcc -working-directory -Xcc /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator -resource-dir /users/redacted/Downloads/Xcode\ 13.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/swift-overrides.hmap -Xcc -I/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Products/Debug/include -Xcc -I/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/DerivedSources-normal/arm64 -Xcc -I/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/DerivedSources/arm64 -Xcc -I/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name SwiftUINavigator -target-sdk-version 12.3 -o /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Build/Intermediates.noindex/SwiftUINavigator.build/Debug/SwiftUINavigator.build/Objects-normal/arm64/NavBar.o -index-unit-output-path /SwiftUINavigator.build/Debug/SwiftUINavigator.build/Objects-normal/arm64/NavBar.o -index-store-path /users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/Index/DataStore -index-system-modules

/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:53:25: error: 'init(systemName:)' is only available in macOS 11.0 or newer
                        Image(systemName: "chevron.backward").foregroundColor(.blue)
                        ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:53:25: note: add 'if #available' version check
                        Image(systemName: "chevron.backward").foregroundColor(.blue)
                        ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:44:18: note: add @available attribute to enclosing instance method
    private func BarLeadingView() -> some View {
                 ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:10:15: note: add @available attribute to enclosing generic struct
public struct NavBar<Content: View>: View {
              ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:63:13: error: closure containing control flow statement cannot be used with result builder 'CommandsBuilder'
            if let view = background {
            ^
SwiftUI.CommandsBuilder:4:30: note: struct 'CommandsBuilder' declared here
@resultBuilder public struct CommandsBuilder {
                             ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:62:9: error: return type of instance method 'BarBackground()' requires that 'EmptyCommands' conform to 'View'
        Group {
        ^
/users/redacted/Library/Developer/Xcode/DerivedData/MyProject-dnphidpimbleicharwshztaycdyg/SourcePackages/checkouts/SwiftUINavigator/SwiftUINavigator/Sources/SwiftUINavigator/NavBar/NavBar.swift:61:37: note: opaque return type declared here
    private func BarBackground() -> some View {
                                    ^~~~~~~~~
```

<img width="629" alt="image" src="https://user-images.githubusercontent.com/3022693/169185961-5f54fe2d-8c83-48b1-b8fb-6da12f70ec3a.png">

**Comment by MalekKamel** [comment]
I have fixed it in version `0.4.0`.
Kindly try and report if there's an issue.

**Comment by bdrelling** [comment]
Still does not compile. One of the errors I initially reported is also still failing.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/3022693/169215186-aa8bc618-f315-4bb9-b266-0e4dcb131f89.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/3022693/169215237-93dd07e4-cef2-4482-bc80-ec0d2dd66f39.png">

I tried in Xcode 13.3 and Xcode 13.4, my target is Mac (not Mac Catalyst). 

And here are my specs:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/3022693/169215348-038e1f79-e0d5-465a-a278-9de562753037.png">

Hope this helps you out.

**Comment by MalekKamel** [comment]
I thought you mean mac Catalyst. macOS support is now available in version `0.8.0`.
